#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/libtsm-dev /usr/share/doc/libtsm4 4.0.2-0.4\~ -- "$@"
# End automatically added section
